### PR TITLE
Leader circle fix

### LINKED ISSUE #713: Add Leadership Circle recognition to website
# Bug Report
## What is the current behavior?
No recognition on [the leadership circle page](www.operationcode.org/leadership_circle), when there should be.

## What is the expected behavior?
Recognition of all donors in the following shape, underneath the first section on www.operationcode.org/leadership_circle

### Simple mock
Screen Shot 2019-08-08 at 2 21 26 PM

### The donor data
[2018 Leadership Circle list.pdf](https://github.com/OperationCode/front-end/files/3441419/2018.Leadership.Circle.list.pdf)

### Other Info
Non-developer members of Operation Code will need to update this data. Please ensure that the donors are placed into a sensible data structure as a separate file, and create a README tutorial next to that file to explain _every single step_ needed for somebody to update the file. Assume the readers know nothing about GitHub, but are able to navigate the browser and will bookmark your README file.

### PR DESCRIPTION
**Pull request by cbituin**
# Description of changes
Hard coded current list of Leadership Circle donors into /leadership_circle.

# Issue Resolved

Fixes #713 

## Screenshots/GIFs

Current view of list:
image

Zoom out for context:
image

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 3a9790d94fa4ea46f7651f2eebf290d081e44a0e

https://deploy-preview-739--operation-code-storybook.netlify.com

File: pages/leadership_circle.js [hunk 1]
```diff
@@ -53,10 +54,64 @@ export default () => (
...
       ]}
     />
+    <Content
+      title="Operation Code Honor Roll"
+      theme="gray"
+      columns={[
+        <Card className={styles.honorRollCard}>
+          <h6>Benefactor ($2500 or more)</h6>
+          <ul className={styles.honorRollList}>
+            <li>Conrad Hollomon</li>
```
Comment (kylemh) [inline pages/leadership_circle.js]: Note the **Other Information** aspect of the original ticket:
```
Non-developer members of Operation Code will need to update this data. Please ensure that the donors are placed into a sensible data structure as a separate file, and create a README tutorial next to that file to explain every single step needed for somebody to update the file. Assume the readers know nothing about GitHub, but are able to navigate the browser and will bookmark your README file.
```

So your'e missing two things

# 1

I recommend taking out all the names as hard-coded HTML and placing it into a `.json` file like so:

```json
{
  "benefactors": [
    "Conrad Hollomon",
    "Chris Todd",
    "Laura Wicket"
  ],
  "patrons": [
    "Liliana Monge',
    "Aaron Sahlstrom",
    "Nic and Gwyn Benders"
  ]
}
```

# 2

You need to create an in-depth README file for non-devs to understand how to update the JSON file.

**Comment by kylemh** [comment]
@cbituin idk what you did, but you've got changes from all over the place now.

**Comment by kylemh** [comment]
#### 📝Changed routes:


| [**/leadership_circle**](https://operation-code-git-leader-circle-fix.operation-code.now.sh/leadership_circle) | [**/styles/leadership_circle**](https://operation-code-git-leader-circle-fix.operation-code.now.sh/styles/leadership_circle) |
|:-:|:-:|
|<a href="https://operation-code-git-leader-circle-fix.operation-code.now.sh/leadership_circle">Screenshot of /leadership_circle</a><br /><sup><a href="https://microlink-cdn.s3.amazonaws.com/s/_mip_MCfLL5uZW/VUthla4mce1rk_">(view full size)</a> |<a href="https://operation-code-git-leader-circle-fix.operation-code.now.sh/styles/leadership_circle">Screenshot of /styles/leadership_circle</a><br /><sup><a href="https://microlink-cdn.s3.amazonaws.com/s/9vC7iQtWa6xRdq/nIBf5kwTuFEPQ_">(view full size)</a> |







Commit 022d5c5eddb02cd0dac99f415747fa606a311578 (https://operation-code-git-leader-circle-fix.operation-code.now.sh).
