### PR TITLE
fix custom tw colors opacity. replace Input css module with tw

### LINKED ISSUE #1882: Replace Input.tsx styles with TailwindCSS
This issue breaks down #1725 into smaller tasks

### PR DESCRIPTION
**Pull request by billy-le**
# Description of changes

convert tailwind.config to ts. updated colors so that using classes like `text-success/50` works.

replaced Input css modules with tw

# Issue Resolved

Fixes #1882

## Screenshots/GIFs

Screenshot 2025-08-09 at 8 32 58 AM

### CODE REVIEW

File: components/Form/Checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ function Checkbox({
   id,
   label,
 }: CheckboxProps) {
-  const hasErrors = errors[name];
+  const hasErrors = Boolean(errors[name]);
```
Comment (kylemh) [inline components/Form/Checkbox/Checkbox.tsx:19]: 🎉

File: components/Form/Input/Input.tsx [hunk 2]
```diff
@@ -34,21 +33,31 @@ function Input({
...
+      >
         <input
           {...field}
           {...props}
-          className={cx(styles.Input, hasValidationStyling, {
-            [styles.valid]: touched[name] && !hasErrors && hasValidationStyling,
-            [styles.invalid]: touched[name] && hasErrors && hasValidationStyling,
-          })}
+          className={cx(
+            'border border-secondary/50 rounded-[3px] text-lg p-2',
```
Comment (kylemh) [inline components/Form/Input/Input.tsx:51]: you can always remove arbitrary values like this unless you think it makes a huge difference
```suggestion
            'border border-secondary/50 rounded-sm text-lg p-2',
```

**Review by kylemh — APPROVED** [review]

File: components/Form/Input/Input.tsx [hunk 3]
```diff
@@ -34,21 +33,31 @@ function Input({
...
+            'disabled:opacity-60 hover:disabled:cursor-not-allowed min-w-[200px]',
```
[the remark this answers is not in the document]
Comment (kylemh) [reply components/Form/Input/Input.tsx]: seems good to me, but use your judgement. if it looks poor because of the tweak, then arbitrary is okay
