### PR TITLE
fix category/languages dropdown issue & refactor useEffect hooks

### LINKED ISSUE #1159: Languages and Category components do not populate when navigating to the page
# Bug Report
## What is the current behavior?
When navigating to https://operationcode.org/resources/1?category=minorities directly, there is nothing populated in the "Category" dropdown. Luckily, it still filters for the correct category, but it does not show in the component and this isn't ideal because there's also nothing telling you what the current filters are (and perhaps the real solution is adding that, I'm not sure).

The same situation happens for the languages dropdown if, for example, you navigate to https://operationcode.org/resources/1?languages=javascript

## What is the expected behavior?
The "Category" dropdown should have "Minorities" selected.

## What steps did you take to get this behavior?
I navigated to the expected page.

### Operating System
N/A
### Browser
N/A
### Is This A Third-Party Issue?

No

### Screenshots

Screen Shot 2020-07-05 at 9 11 04 PM
Screen Shot 2020-07-05 at 9 12 45 PM

### PR DESCRIPTION
**Pull request by chynh**
# Description of changes

This PR mainly takes care of #1159 where "categories" and "languages" dropdown are not populated when navigating to resource page with params in URL string. It is accomplished by creating `initialValues` with data extracted from query params. 

It does introduce two additional changes:

1. Refactor of `useEffect`

- `getResourcesByCategories` and `getResourcesByLanguages` run every time `query` changes which is somewhat unnecessary. Also, there was a memory leak warning in the console if you were to navigate to another page after being on resources page as shown below.
Screen Shot 2020-07-19 at 2 02 02 PM

As a solution, I refactored the `useEffect` hook so that the above API calls would only run on the initial page load. 

2. Fix data testid
- Fix `data-test-isPaid` so that the below warning is not produced.
Screen Shot 2020-07-19 at 2 01 34 PM
  

# Issue Resolved

Fixes #1159

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit ff115e848c27daeccfac3a2f4c131ead99c79c48

https://deploy-preview-1169--operation-code-storybook.netlify.app

**Comment by kylemh** [comment]
#### 📝Changed routes:


| [**/resources/\[page\]**](https://operation-code-git-fixcategorydropdown.operation-code.now.sh/resources/[page]) |
|:-:|
|<a href="https://operation-code-git-fixcategorydropdown.operation-code.now.sh/resources/[page]">Screenshot of /resources/[page]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/2RnNQXUkTJ5FTTV0NhcfY6WtmxU_.png">(view full size)</a> |







Commit 34ec735bdc4298b9597cdddda81830ca33a0cbd8 (https://operation-code-git-fixcategorydropdown.operation-code.now.sh).

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 34ec735bdc4298b9597cdddda81830ca33a0cbd8

https://deploy-preview-1169--operation-code-storybook.netlify.app

File: pages/resources/[page].js [hunk 1]
```diff
@@ -56,10 +56,10 @@ function Resources() {
...
 
   const initialValues = {
-    category: [],
-    q: '',
-    languages: [],
-    paid: '',
+    category: category || '',
+    q: q || '',
+    languages: Array.isArray(languages) ? languages : [languages].filter(Boolean),
+    paid: paid || '',
```
Comment (kylemh) [inline pages/resources/[page].js:62]: I hope you don't mind, but I got rid of the nullish coalescing here. It's totally valid, but I'm trying to keep less sugar out of the codebase. I should add a lint rule to prevent it and optional chaining.
