### PR TITLE
Fix #1232 Call gtag only when it available

### LINKED ISSUE #1232: UpgradeBrowserOverlay and Modal stories are broken
# Bug Report
## What is the current behavior?
The following stories are broken due to a run-time error related to `gtag` being undefined (which makes sense cuz we dont ship google analytics to our Storybook).

- [UpgradeBrowserOverlay](https://storybook.operationcode.org/?path=/story/upgradebrowseroverlay--default)
- [Modal](https://storybook.operationcode.org/?path=/story/modal--default)

## What is the expected behavior?
The UI renders for both of these stories and does not care about `gtag`.

### PR DESCRIPTION
**Pull request by tranlehaiquan**
# Description of changes

fixes #1232  by call gtag only when it avaiable

# Issue Resolved

Fixes #1232  by call gtag only when it avaiable

## Screenshots/GIFs

image

### CODE REVIEW

File: common/utils/thirdParty/gtag.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const log = ({ methodName, ...rest }) => {
 const pageView = (url, isModalView = false) => {
   log({ methodName: 'pageview', url, isModalView });
 
-  if (isProduction) {
+  if (isProduction && window.gtag) {
```
Comment (kylemh) [inline common/utils/thirdParty/gtag.js:27]: Can you add this for all the (isProduction) conditionals in this file? Even better might be: `isProduction && !!window && !!window.gtag`

**Review by kylemh — APPROVED** [review]
Thanks so much for your 🎃 Hacktoberfest🎃&nbsp; contribution!

If you weren't aware, we're offering prizes too! You can read about the details [here](https://github.com/OperationCode/START_HERE#-hacktoberfest-).

Regardless, you've contributed, and we recommend you set yourself a reminder to submit the aforementioned form after November 1st (or after you meet all the criteria).
